# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

# .goreleaser.yml
builds:
  - id: default
    main: ./cmd/kcl/main.go
    binary: kcl
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X kcl-lang.io/cli/pkg/version.version={{.Version}}"

archives:
  - id: default
    builds:
      - default
    name_template: "kcl-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: kcl-lang
      name: homebrew-tap
    url_template: "https://github.com/kcl-lang/cli/releases/download/{{ .Tag }}/kcl-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    download_strategy: CurlDownloadStrategy
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: GoReleaser Bot
      email: goreleaser@carlosbecker.com
    folder: HomebrewFormula
    homepage: "https://github.com/kcl-lang/kcl"
    description: "KCL Command Line Interface"
    license: "Apache License"
    skip_upload: false
    test: |
      system "#{bin}/kcl version"

scoop:
  url_template: "https://github.com/kcl-lang/cli/releases/download/{{ .Tag }}/kcl-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  bucket:
    owner: kcl-lang
    name: scoop-bucket
    branch: main
    token: "{{ .Env.GITHUB_TOKEN }}"
  folder: Scoops
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: "Scoop update for kcl version {{ .Tag }}"
  homepage: "http://github.com/kcl-lang/kcl"
  description: "KCL Command Line Interface"
  license: Apache License 2.0
