# Reference from:
# https://goreleaser.com/ci/actions/
name: Release
on:
  push:
permissions:
  contents: write
jobs:
  Publish: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.11.2
          install: true

      # <--- Login, build and push image to Docker Hub --->
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kcllang/kcl
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kcllang/kcl
